version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4173:4173'
    volumes:
      - .:/news-feed
      - /news-feed/node_modules
    stdin_open: true
    tty: true
